# Generated by Django 4.2.4 on 2023-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name': 'CMS'},
        ),
    ]
