# Generated by Django 4.2.4 on 2024-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
