# Generated by Django 4.2.4 on 2024-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_program_programphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='maks size 16:9', null=True, upload_to='images'),
        ),
    ]
